#  ____ ____ ____ ____ ____ ____ 
# ||L |||e |||m |||u |||r |||s ||
# ||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|

# variables.toml file
# based on Catppuccin Mocha

######################################
# Color variables
background="#1e1e2e"
text="#cdd6f4"
subtext="#6c7086"
highlight="#f5c2e7"
error="#f38ba8"
######################################
