#  ____ ____ ____ ____ ____ ____ 
# ||L |||e |||m |||u |||r |||s ||
# ||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|

# variables.toml file

######################################
# Color variables

# The only supported colors in tty:
# - black
# - white
# - (dark) gray
# - (light) red
# - (light) blue
# - (light) green
# - (light) magenta
# - (light) cyan
# - (light) yellow
# - orange

background="black"
text="white"
subtext="gray"
highlight="light magenta"
error="red"
######################################
